<?php
    /*API KEY*/
    define(APIKEY,"?api_key=934e435260635d2b56c3426a0d54dac4");
    /*PAGINA PRINCIPAL*/
    define(PAGE,"https://api.themoviedb.org");
    /*IDIOMA ESPAÑOL*/
    define(ESP,"&language=es-ES");
    /*IDIOMA INGLES*/
    define(ENG,"&language=en-EN")

    /*ESTE ES EL LINK PARA OBTENER LAS PELICULAS QUE ESTAN EN CARTELERA 
    CUANDO SE LO USA HAY QUE CONCATENARLE UN NUMERO QUE SERIA LA PAGINA
    EJEMPLO: LASTMVS."3" */
    define(LASTMVS,PAGE."/3/movie/now_playing".APIKEY.ENG."&page=");
    
    /*ESTE ES EL LINK PARA BUSCAR UNA PELICULA, SE LE TIENE QUE CONCATENAR EL ID DE LA PELICULA
    QUE SE QUIERE BUSCAR LUEGO EL API KEY Y POR ULTIMO EL LENGUAJE QUE SE DESEA
    EJEMPLO: SERCHM."5".APIKEY.ESP */
    define(SERCHM,"https://api.themoviedb.org/3/movie/");

    /*ESTE LINK ES PARA BUSCAR LA IMAGEN DE UNA PELICULA SE LE DEBE CONCATENAR EL TAMAÑO DE LA IMAGEN
    (ALGUNOS VALORES NO LOS PERMITE) Y LUEGO UNA BARRA Y POR ULTIMO EL "POSTER PATH" QUE ESO ESTA
    EN EL JSON DE CADA PELICULA
    EJEMPLO: IMGM."500"."/".kqjL17yufvn9OVLyXYpvtyrFfak.jpg */
    define(IMGM,"https://image.tmdb.org/t/p/w");
?>